### ISSUE TITLE
مشکل لینک‌های فارسی

### ISSUE THREAD

**Issue by smmoosavi** [smmsadrnezh/persian-startups#2]
تمام لینک‌های قسمت پایین که فارسی هستند در گیتهاب اشتباه نمایش داده می‌شود

**Comment by smmsadrnezh** [comment]
موارد فارسی از داخل لیست اصلی حذف شدن تا لینکشون پیدا شه و ترجمه بشن بعد دوباره اضافه شن به لیست اصلی.
